<Project>
  <Import Project="../Directory.Build.props" />
  <PropertyGroup>
    <DirectoryBuildPropsPath>$(MSBuildThisFileDirectory)../node_modules/@tsonic/csharp-runtime/Directory.Build.props</DirectoryBuildPropsPath>
    <TsonicRuntimeArtifactsPath>$(MSBuildThisFileDirectory)../.tsonic/cache/csharp/runtime/</TsonicRuntimeArtifactsPath>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)../node_modules/@tsonic/csharp-runtime/src/Tsonic.CSharp.Runtime/Tsonic.CSharp.Runtime.csproj" />
</Project>
